
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author USER
 */
public class dashboard extends javax.swing.JFrame {
Connection con=null;
studentlogin ob = new studentlogin();
CONNECTION obj = new CONNECTION();
    /**
     * Creates new form dashboard
     */
    public dashboard() throws SQLException {
          super("HOSPITAL MANAGEMENT SYSTEM");
          
       
      initComponents();
         con = DriverManager.getConnection("jdbc:mysql://localhost:3306/id9752685_ams","id9752685_root","Vivek@123");
         call();
    }
    
    void call(){
     try{
            String query = "select * from reg";
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query);
            int c=0;
            while(rs.next()){

                String name = rs.getString(1);
                 String gender= rs.getString(2);
                  String email = rs.getString(3);
                   String phone = rs.getString(4);
                    String add = rs.getString(5);
                      String courses = rs.getString(6);
              
                if(L3.getText().equalsIgnoreCase(email)){
                       L1.setText(name);
                         L2.setText(gender);   
                     L3.setText(email);
                       L4.setText(phone);
                       L5.setText(add);
                       L6.setText(courses);
                       
                   // dispose();
                    c=1;
                    break;
                }
               

            }
           
            
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleframe = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        titlename1 = new javax.swing.JLabel();
        titlename = new javax.swing.JLabel();
        titlename2 = new javax.swing.JLabel();
        titlename3 = new javax.swing.JLabel();
        titlename4 = new javax.swing.JLabel();
        titlename5 = new javax.swing.JLabel();
        titlename6 = new javax.swing.JLabel();
        titlename8 = new javax.swing.JLabel();
        L3 = new javax.swing.JLabel();
        L4 = new javax.swing.JLabel();
        L2 = new javax.swing.JLabel();
        L5 = new javax.swing.JLabel();
        L6 = new javax.swing.JLabel();
        L1 = new javax.swing.JLabel();
        titlename9 = new javax.swing.JLabel();
        L7 = new javax.swing.JLabel();
        titlename11 = new javax.swing.JLabel();
        titlename12 = new javax.swing.JLabel();
        titlename13 = new javax.swing.JLabel();
        titlename14 = new javax.swing.JLabel();
        titlename16 = new javax.swing.JLabel();
        c1 = new javax.swing.JComboBox<>();
        titlename17 = new javax.swing.JLabel();
        c2 = new javax.swing.JComboBox<>();
        titlename18 = new javax.swing.JLabel();
        c3 = new javax.swing.JComboBox<>();
        titlename19 = new javax.swing.JLabel();
        c4 = new javax.swing.JComboBox<>();
        titlename20 = new javax.swing.JLabel();
        c5 = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        t4 = new javax.swing.JTextField();
        titlename15 = new javax.swing.JLabel();
        titlename21 = new javax.swing.JLabel();
        titlename22 = new javax.swing.JLabel();
        titlename23 = new javax.swing.JLabel();
        c6 = new javax.swing.JComboBox<>();
        titlename24 = new javax.swing.JLabel();
        c7 = new javax.swing.JComboBox<>();
        titlename25 = new javax.swing.JLabel();
        c8 = new javax.swing.JComboBox<>();
        titlename26 = new javax.swing.JLabel();
        c9 = new javax.swing.JComboBox<>();
        titlename27 = new javax.swing.JLabel();
        c10 = new javax.swing.JComboBox<>();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titleframe.setBackground(new java.awt.Color(0, 153, 153));
        titleframe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        titleframe.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        logo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        logo.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        titlename1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        titlename1.setForeground(new java.awt.Color(255, 255, 255));
        titlename1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlename1.setText("ADMISSION  MANAGEMENT SYSTEM");
        titlename1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        titlename1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        titlename1.setPreferredSize(new java.awt.Dimension(450, 28));

        javax.swing.GroupLayout titleframeLayout = new javax.swing.GroupLayout(titleframe);
        titleframe.setLayout(titleframeLayout);
        titleframeLayout.setHorizontalGroup(
            titleframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleframeLayout.createSequentialGroup()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 209, Short.MAX_VALUE)
                .addComponent(titlename1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(410, 410, 410))
        );
        titleframeLayout.setVerticalGroup(
            titleframeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleframeLayout.createSequentialGroup()
                .addComponent(logo, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(titleframeLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(titlename1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(titleframe, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        titlename.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        titlename.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlename.setText("EMAIL:");
        titlename.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        titlename.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        titlename.setPreferredSize(new java.awt.Dimension(450, 28));
        getContentPane().add(titlename, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 110, -1));

        titlename2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        titlename2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlename2.setText("STUDENT  INFORMATION :");
        titlename2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        titlename2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        titlename2.setPreferredSize(new java.awt.Dimension(450, 28));
        getContentPane().add(titlename2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, 370, -1));

        titlename3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        titlename3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlename3.setText("STUDENT  INFORMATION :");
        titlename3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        titlename3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        titlename3.setPreferredSize(new java.awt.Dimension(450, 28));
        getContentPane().add(titlename3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 90, 370, -1));

        titlename4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        titlename4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlename4.setText("PHONE:");
        titlename4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        titlename4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        titlename4.setPreferredSize(new java.awt.Dimension(450, 28));
        getContentPane().add(titlename4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 110, -1));

        titlename5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        titlename5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlename5.setText("GENDER:");
        titlename5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        titlename5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        titlename5.setPreferredSize(new java.awt.Dimension(450, 28));
        getContentPane().add(titlename5, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 150, 110, -1));

        titlename6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        titlename6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlename6.setText("ADDRESS:");
        titlename6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        titlename6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        titlename6.setPreferredSize(new java.awt.Dimension(450, 28));
        getContentPane().add(titlename6, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 120, -1));

        titlename8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        titlename8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlename8.setText("NAME:");
        titlename8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        titlename8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        titlename8.setPreferredSize(new java.awt.Dimension(450, 28));
        getContentPane().add(titlename8, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 100, -1));

        L3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        L3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        L3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        L3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        L3.setPreferredSize(new java.awt.Dimension(450, 28));
        getContentPane().add(L3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 190, 390, -1));

        L4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        L4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        L4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        L4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        L4.setPreferredSize(new java.awt.Dimension(450, 28));
        getContentPane().add(L4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, 390, -1));

        L2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        L2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        L2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        L2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        L2.setPreferredSize(new java.awt.Dimension(450, 28));
        getContentPane().add(L2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 390, -1));

        L5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        L5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        L5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        L5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        L5.setPreferredSize(new java.awt.Dimension(450, 28));
        getContentPane().add(L5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 270, 390, -1));

        L6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        L6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        L6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        L6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        L6.setPreferredSize(new java.awt.Dimension(450, 28));
        getContentPane().add(L6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 390, -1));

        L1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        L1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        L1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        L1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        L1.setPreferredSize(new java.awt.Dimension(450, 28));
        getContentPane().add(L1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 390, -1));

        titlename9.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        titlename9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlename9.setText("COURSE");
        titlename9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        titlename9.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        titlename9.setPreferredSize(new java.awt.Dimension(450, 28));
        getContentPane().add(titlename9, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 110, -1));

        L7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        L7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        L7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        L7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        L7.setPreferredSize(new java.awt.Dimension(450, 28));
        getContentPane().add(L7, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 390, -1));

        titlename11.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        titlename11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlename11.setText("COURSE FEE :");
        titlename11.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        titlename11.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        titlename11.setPreferredSize(new java.awt.Dimension(450, 28));
        getContentPane().add(titlename11, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 550, 170, -1));

        titlename12.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        titlename12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlename12.setText("Doc1.");
        titlename12.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        titlename12.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        titlename12.setPreferredSize(new java.awt.Dimension(450, 28));
        getContentPane().add(titlename12, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 420, 60, 20));

        titlename13.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        titlename13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlename13.setText("CURICU. FEE:");
        titlename13.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        titlename13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        titlename13.setPreferredSize(new java.awt.Dimension(450, 28));
        getContentPane().add(titlename13, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 590, 170, -1));

        titlename14.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        titlename14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlename14.setText("<html>\n<body><u>Final information and payment dashboard :</u>");
        titlename14.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        titlename14.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        titlename14.setPreferredSize(new java.awt.Dimension(450, 28));
        getContentPane().add(titlename14, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 370, 630, -1));

        titlename16.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        titlename16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlename16.setText("DOCUMENT:");
        titlename16.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        titlename16.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        titlename16.setPreferredSize(new java.awt.Dimension(450, 28));
        getContentPane().add(titlename16, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, 150, -1));

        c1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "----", "10Th", "12Th", "MCA", "BCA", "BBA", "MBA", "BSC", "MSC", "BA", "B.COM", "B.TECH", "M.TECH", "M.COM", "DIPLOMA" }));
        getContentPane().add(c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 420, 100, 20));

        titlename17.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        titlename17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlename17.setText("Doc2.");
        titlename17.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        titlename17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        titlename17.setPreferredSize(new java.awt.Dimension(450, 28));
        getContentPane().add(titlename17, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 420, 70, 20));

        c2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "----", "10Th", "12Th", "MCA", "BCA", "BBA", "MBA", "BSC", "MSC", "BA", "B.COM", "B.TECH", "M.TECH", "M.COM", "DIPLOMA" }));
        getContentPane().add(c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 420, 100, -1));

        titlename18.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        titlename18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlename18.setText("Doc3.");
        titlename18.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        titlename18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        titlename18.setPreferredSize(new java.awt.Dimension(450, 28));
        getContentPane().add(titlename18, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 420, 70, 20));

        c3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "----", "10Th", "12Th", "MCA", "BCA", "BBA", "MBA", "BSC", "MSC", "BA", "B.COM", "B.TECH", "M.TECH", "M.COM", "DIPLOMA" }));
        getContentPane().add(c3, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 420, 100, -1));

        titlename19.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        titlename19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlename19.setText("Doc4.");
        titlename19.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        titlename19.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        titlename19.setPreferredSize(new java.awt.Dimension(450, 28));
        getContentPane().add(titlename19, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 420, 50, 20));

        c4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "----", "10Th", "12Th", "MCA", "BCA", "BBA", "MBA", "BSC", "MSC", "BA", "B.COM", "B.TECH", "M.TECH", "M.COM", "DIPLOMA" }));
        getContentPane().add(c4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 420, 80, -1));

        titlename20.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        titlename20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlename20.setText("Doc5.");
        titlename20.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        titlename20.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        titlename20.setPreferredSize(new java.awt.Dimension(450, 28));
        getContentPane().add(titlename20, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 420, 50, 20));

        c5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "----", "10Th", "12Th", "MCA", "BCA", "BBA", "MBA", "BSC", "MSC", "BA", "B.COM", "B.TECH", "M.TECH", "M.COM", "DIPLOMA" }));
        getContentPane().add(c5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 420, 80, -1));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("SUBMIT");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Clear");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        titlename15.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        titlename15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlename15.setText("TOTAL FEE:");
        titlename15.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        titlename15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        titlename15.setPreferredSize(new java.awt.Dimension(450, 28));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(192, Short.MAX_VALUE)
                .addComponent(titlename15, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(t4, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(143, 143, 143)
                .addComponent(jButton1)
                .addGap(138, 138, 138)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(293, 293, 293))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(titlename15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 620, 1450, 130));

        titlename21.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        titlename21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlename21.setText("REG. FEE:");
        titlename21.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        titlename21.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        titlename21.setPreferredSize(new java.awt.Dimension(450, 28));
        getContentPane().add(titlename21, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 510, 120, -1));

        titlename22.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        titlename22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlename22.setText("Id1.");
        titlename22.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        titlename22.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        titlename22.setPreferredSize(new java.awt.Dimension(450, 28));
        getContentPane().add(titlename22, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 470, 60, 20));

        titlename23.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        titlename23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlename23.setText("ID:");
        titlename23.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        titlename23.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        titlename23.setPreferredSize(new java.awt.Dimension(450, 28));
        getContentPane().add(titlename23, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 460, 50, -1));

        c6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---------", "Adhar Card", "Voter Id", "Driving Liacence", "Pan Card", "College Id Card" }));
        c6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c6ActionPerformed(evt);
            }
        });
        getContentPane().add(c6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 470, 100, 20));

        titlename24.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        titlename24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlename24.setText("Id2.");
        titlename24.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        titlename24.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        titlename24.setPreferredSize(new java.awt.Dimension(450, 28));
        getContentPane().add(titlename24, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 470, 70, 20));

        c7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---------", "Adhar Card", "Voter Id", "Driving Liacence", "Pan Card", "College Id Card" }));
        getContentPane().add(c7, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 470, 100, -1));

        titlename25.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        titlename25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlename25.setText("Id3.");
        titlename25.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        titlename25.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        titlename25.setPreferredSize(new java.awt.Dimension(450, 28));
        getContentPane().add(titlename25, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 470, 70, 20));

        c8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---------", "Adhar Card", "Voter Id", "Driving Liacence", "Pan Card", "College Id Card" }));
        getContentPane().add(c8, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 470, 100, -1));

        titlename26.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        titlename26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlename26.setText("Id4.");
        titlename26.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        titlename26.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        titlename26.setPreferredSize(new java.awt.Dimension(450, 28));
        getContentPane().add(titlename26, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 470, 50, 20));

        c9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---------", "Adhar Card", "Voter Id", "Driving Liacence", "Pan Card", "College Id Card" }));
        getContentPane().add(c9, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 470, 80, -1));

        titlename27.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        titlename27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titlename27.setText("Id5.");
        titlename27.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        titlename27.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        titlename27.setPreferredSize(new java.awt.Dimension(450, 28));
        getContentPane().add(titlename27, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 470, 50, 20));

        c10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---------", "Adhar Card", "Voter Id", "Driving Liacence", "Pan Card", "College Id Card" }));
        getContentPane().add(c10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 470, 80, -1));
        getContentPane().add(t1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 510, 280, 40));
        getContentPane().add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 550, 280, 30));

        t3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t3ActionPerformed(evt);
            }
        });
        getContentPane().add(t3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 580, 280, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        
        
        String a, b, c,d ;
        a = t1.getText();
        b=t2.getText();
        c=t3.getText();
   int sum = Integer.parseInt(a)+Integer.parseInt(b)+Integer.parseInt(c);
         String valu = String.valueOf(sum);
         Thread ab = new Thread();
         ab.start();
     t4.setText(valu);
        try {
        Thread.sleep(3000);
    } catch (InterruptedException ex) {
        Logger.getLogger(dashboard.class.getName()).log(Level.SEVERE, null, ex);
    }
        try {
obj.thequery("insert into finaladdmision () values('"+c1.getSelectedItem().toString()+"' ,'"+c2.getSelectedItem().toString()+"' , '"+c3.getSelectedItem().toString()+"' , '"+c4.getSelectedItem().toString()+"' , '"+c5.getSelectedItem().toString()+"' , '"+c6.getSelectedItem().toString()+"' , '"+c7.getSelectedItem().toString()+"' , '"+c8.getSelectedItem().toString()+"' , '"+c9.getSelectedItem().toString()+"' , '"+c10.getSelectedItem().toString()+"' , '"+t1.getText()+"' ,'"+t2.getText()+"' , '"+t3.getText()+"' , '"+t4.getText()+"')");
String name = t2.getText();
JOptionPane.showMessageDialog(null, "Your Admission mang. your Account has  been been finally successfully.");
HOME regFace =new HOME();
regFace.setVisible(true);
this.dispose();
}
catch(Exception ex){
}
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        
    }//GEN-LAST:event_jButton2MouseClicked

    private void t3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t3ActionPerformed

    private void c6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new dashboard().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(dashboard.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel L1;
    public javax.swing.JLabel L2;
    public javax.swing.JLabel L3;
    public javax.swing.JLabel L4;
    public javax.swing.JLabel L5;
    public javax.swing.JLabel L6;
    public javax.swing.JLabel L7;
    private javax.swing.JComboBox<String> c1;
    private javax.swing.JComboBox<String> c10;
    private javax.swing.JComboBox<String> c2;
    private javax.swing.JComboBox<String> c3;
    private javax.swing.JComboBox<String> c4;
    private javax.swing.JComboBox<String> c5;
    private javax.swing.JComboBox<String> c6;
    private javax.swing.JComboBox<String> c7;
    private javax.swing.JComboBox<String> c8;
    private javax.swing.JComboBox<String> c9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logo;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JPanel titleframe;
    private javax.swing.JLabel titlename;
    private javax.swing.JLabel titlename1;
    private javax.swing.JLabel titlename11;
    private javax.swing.JLabel titlename12;
    private javax.swing.JLabel titlename13;
    private javax.swing.JLabel titlename14;
    private javax.swing.JLabel titlename15;
    private javax.swing.JLabel titlename16;
    private javax.swing.JLabel titlename17;
    private javax.swing.JLabel titlename18;
    private javax.swing.JLabel titlename19;
    private javax.swing.JLabel titlename2;
    private javax.swing.JLabel titlename20;
    private javax.swing.JLabel titlename21;
    private javax.swing.JLabel titlename22;
    private javax.swing.JLabel titlename23;
    private javax.swing.JLabel titlename24;
    private javax.swing.JLabel titlename25;
    private javax.swing.JLabel titlename26;
    private javax.swing.JLabel titlename27;
    private javax.swing.JLabel titlename3;
    private javax.swing.JLabel titlename4;
    private javax.swing.JLabel titlename5;
    private javax.swing.JLabel titlename6;
    private javax.swing.JLabel titlename8;
    private javax.swing.JLabel titlename9;
    // End of variables declaration//GEN-END:variables
}
